<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">  
    <link href="https://chatcompose.azureedge.net/static/all/global/export/css/main.5b1bd1fd.css" rel="stylesheet">    
    <script async type="text/javascript" src="https://chatcompose.azureedge.net/static/all/global/export/js/main.a7059cb5.js?user=Eduardo83728367&lang=PT" user="Eduardo83728367" lang="PT"></script>  </head>
    
    <style>
        * {
  margin: 0;
  padding: 0;
  font-family: 'Roboto', sans-serif;
}

body {
    background: url("https://i.ibb.co/XjN5064/katsiaryna-endruszkiewicz-pvhotwuk-Sww-unsplash.jpg");
    background-size:100% 100%;
    background-repeat:no-repeat;
    background-attachment: fixed
  
}

.container {
  display: flex;
  justify-content: center;
  width: 100%;
  margin-top: 150px;
}

.card {
  background-color: #ffffffc2;
  padding: 30px;
  border-radius: 4%;
  box-shadow: 3px 3px 1px 0px #00000060
}

h1{
  text-align: center;
  margin-bottom: 20px;
  color: #851a0d
}

.label-float input{
  width: 100%;
  padding: 5px 5px;
  display: inline-block;
  border: 0;
  background-color: transparent;
  outline: none;
  min-width: 180px;
  font-size: 16px;
  transition: all .3s ease-out;
  border-radius: 0;
  
}

.label-float{
  position: relative;
  padding-top: 13px;
  margin-top: 5%;
  margin-bottom: 5%;
}

.label-float label{
  color: #851a0d;
  position: absolute;
  top: 0;
  left: 0;
  margin-top: 13px;
  transition: all .3s ease-out;
}

.label-float input:focus + label,
.label-float input:valid + label{
  font-size: 13px;
  margin-top: 0;
  color: #851a0d
}
  
input:valid {
    border-bottom: 2px solid #26a69a;
    pointer-events: visible;  
  }
  
  input:invalid {
      border-bottom: 2px solid #851a0d;
  }

button{
  background-color: transparent;
  border-color: #851a0d;
  box-shadow: 2px 2px 1px 0px #00000060;
  color: #851a0d;
  padding: 7px;
  font-weight: bold;
  font-size: 12pt;
  margin-top: 20px;
  border-radius: 4px;
  cursor: pointer;
  outline: none;
  transition: all .4s ease-out;
}

button:hover{
  background-color: #851a0d;
  color: #fff;
}

.justify-center{
  display: flex;
  justify-content:center;
}

hr{
  margin-top: 10%;
  margin-bottom: 10%;
  width: 60%;
}

p{
  color: #851a0d;
  font-size: 14pt;
  text-align: center;
}

a{
  color: #500d04;
  font-weight: bold;
  text-decoration: none;
  transition: all .3s ease-out;
}

a:hover{
  color: #851a0d;
}

 #msgError{
  text-align: center;
  color: #ff0000;
  background-color: #ffbbbb;
  padding: 10px;
  border-radius: 4px;
  display: none;
}

    </style>
    <body>
        <div class='container'>
            <div class='card'>
                <div id="bg"></div>
                <h1> Logar </h1>
                <form action="logar" method="post">
                <div class='label-float'>
                    <input type='text' name="nome_User" id='user' paceholder='' required>
                    <label id='userLabel' for='usuario'>Usuario</label>
                </div>
                <div class='label-float'>
                    <input type='password' name='password_User' id='password' paceholder='' required>
                    <label id='senhaLabel' for='senha'>Senha</label>
                </div> 
                <div class='justify-center'>
                    <button type="submit"> Entrar </button>
                </div>  
                <div class='justify-center'>
                    <hr>
                </div>
                <p> Nao tem uma conta?
                    <a href=''> Cadastre-se </a>
                </p>
            </div>
        </form>
        </div>
    </body>
</html> 